export { openApiDocs } from './plugin'
export type { OpenApiDocsPluginOptions } from './plugin'
export { buildSidebar } from './sidebar'
export { generatePages } from './page-generator'
export { specsVirtualModule, VIRTUAL_SPECS_ID } from './virtual-module'
export { scanForBrokenEmbeds, type BrokenEmbed } from './scanner'
export { parseSpec } from '../parser/index'
export { ParseError } from '../parser/types'
export { extractChangelog } from '../changelog/extractor'
export type { SpecChangelog, ChangelogEntry } from '../changelog/types'
