name: Feature request
description: Suggest a new feature or improvement
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What are you trying to do that isn't possible or is harder than it should be?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: How you'd like it to work.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other approaches you've tried or thought about.
